FROM maven AS MAVEN_BUILD
WORKDIR /app

COPY . /app
RUN mvn clean package -DskipTests


FROM openjdk:17
WORKDIR /app
COPY --from=MAVEN_BUILD /app/target/*.jar /app.jar
EXPOSE 8080

ENTRYPOINT ["sh" ,"-c"]
CMD ["exec java $JAVA_OPTS -jar /app.jar  $JAVA_CONFIGS"]